id: IDEE6971B
ocr_import_info:
  timestamp: '2023-06-18T17:56:26.130290+00:00'
  batch_id: batch-5635
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Peche job
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-18 22:32:59.384731+00:00
last_modified: 2023-06-18 22:32:59.384740+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W21953
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW21953
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆེན་འབར་བའི་རྡོ་རྗེའི་རྣམ་ཐར།
  languages:
  - bo
  author: གཏེར་ཆེན་འབར་བའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9260012709798301
  ocr_word_median_confidence_index: 0.9780973
bases:
  I3851:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3851
      total_pages: 590
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3851.txt
    statistics:
      ocr_word_median_confidence_index: 0.9780973
      ocr_word_mean_confidence_index: 0.9260012709798301
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
